workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile_app
          flutter pub get

      - name: Build APK
        script: |
          cd mobile_app
          flutter build apk --release
    artifacts:
      - mobile_app/build/app/outputs/flutter-apk/*.apk
